member:
  property: Member Profile Dev

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/intranetdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  security:
    user:
      name: ""
      password: ""
webclient:
  base-url: http://localhost:8081