spring:
  application:
    name: member
management:
  graphite:
    metrics:
      export:
        enabled: false
  security:
    user:
      name: ""
      password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysql:3306/intranetdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "root"

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}