member:
  property: Member Profile Prod

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/intranetdb
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  security:
    user:
      name: ""
      password: ""
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
