spring:
  application:
    name: user
management:
  graphite:
    metrics:
      export:
        enabled: false
  security:
    user:
      name: ""
      password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysql:3306/intranetdb
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}